version: '3.4'

services:
  db:
    image: postgres:15.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: max
      POSTGRES_DB: searchgame
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data:Z"
